// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIeroI9AzJsHiCjPf4R3LCKP_wuhQRlYg',
    appId: '1:746500158978:web:e37f6255a1b9cc2283191b',
    messagingSenderId: '746500158978',
    projectId: 'spendly-b6a39',
    authDomain: 'spendly-b6a39.firebaseapp.com',
    storageBucket: 'spendly-b6a39.appspot.com',
    measurementId: 'G-SYC114LSBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPO01U_H34Ksbam7NB4jrdB9jkq_e_eRo',
    appId: '1:746500158978:android:12a790f2fa8bcb7083191b',
    messagingSenderId: '746500158978',
    projectId: 'spendly-b6a39',
    storageBucket: 'spendly-b6a39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3orntlXZcjoDWAKlIlQfe3gTKyKpYV7o',
    appId: '1:746500158978:ios:2a6cbd592e86db8983191b',
    messagingSenderId: '746500158978',
    projectId: 'spendly-b6a39',
    storageBucket: 'spendly-b6a39.appspot.com',
    iosBundleId: 'com.example.spendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3orntlXZcjoDWAKlIlQfe3gTKyKpYV7o',
    appId: '1:746500158978:ios:c39c72f2ac64ca0a83191b',
    messagingSenderId: '746500158978',
    projectId: 'spendly-b6a39',
    storageBucket: 'spendly-b6a39.appspot.com',
    iosBundleId: 'com.example.spendly.RunnerTests',
  );
}
